const CONFIG = {
    introTitle: 'Tún ơi!',
    introDesc: `Gặp nhau từ lần đầu tiên đã thấy mọi thứ thật diệu kì mong người thương tình mà hãy trả lời tui `,
    btnIntro: 'Đunt care',
    title: 'Xin hãy tha thứ cho C mòaaaa 😢',
    desc: 'Lòng Tún rộng bao la như biển Thái Bình ~ ',
    btnYes: 'Ừa Tún tha <33',
    btnNo: 'Đừng xin lỗi nữa, cứ thế mà đi, đừng nói lời chi...',
    question:'Tạ chủ long ân 😽 <3',
    btnReply: 'Gửi cho C',
    reply: 'Giựn ',
    mess: 'C biết mà 🥰. Yêu em nhiều nhiều 😘😘',
    messDesc: 'Tối nay 9h C nhắn công chúa.',
    btnAccept: 'Okiiiii lun <3',
    messLink: 'https://www.facebook.com/haineocon'}
